import { app, dialog, type BrowserWindow } from "electron";
import { randomUUID } from "node:crypto";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import { basename, isAbsolute, join, resolve } from "node:path";
import { addProjectThreadSchema, addStandaloneThreadSchema, messagesStoreSchema, parseInput, projectCloneSchema, projectCreateSchema, projectIdSchema, projectImportSchema, projectThreadUpdateSchema, threadUpdateSchema } from "../shared/ipc";
import type { StateDatabase, StoredProject, StoredThread, StoredWorkspace } from "./state-database";
import type { IpcRegistrar, RunProcess } from "./ipc-types";
import type { NativeHistoryService } from "./native-history";

type Dependencies = { getWindow: () => BrowserWindow | null; loadWorkspace: () => Promise<StoredWorkspace>; saveWorkspace: (workspace: StoredWorkspace) => Promise<void>; stateDatabase: () => StateDatabase; nativeHistory?: NativeHistoryService; runProcess: RunProcess; gitExecutable: () => string };

function projectName(value: string): string { const clean = value.trim(); if (!clean || clean.length > 80 || clean === "." || clean === ".." || /[\\/:*?"<>|]/.test(clean)) throw new Error("项目名称无效"); return clean; }
async function exists(path: string): Promise<boolean> { try { await stat(path); return true; } catch { return false; } }
async function createTemplate(path: string, template: "empty" | "react" | "node", name: string): Promise<void> {
  if (template === "react") { await mkdir(join(path, "src"), { recursive: true }); await writeFile(join(path, "package.json"), `${JSON.stringify({ name, private: true, type: "module", scripts: { dev: "vite", build: "vite build" }, dependencies: { "@vitejs/plugin-react": "latest", vite: "latest", react: "latest", "react-dom": "latest" } }, null, 2)}\n`); await writeFile(join(path, "index.html"), '<div id="root"></div><script type="module" src="/src/main.jsx"></script>\n'); await writeFile(join(path, "src/main.jsx"), 'import React from "react";\nimport { createRoot } from "react-dom/client";\ncreateRoot(document.getElementById("root")).render(<main>Hello</main>);\n'); }
  else if (template === "node") { await writeFile(join(path, "package.json"), `${JSON.stringify({ name, private: true, type: "module", scripts: { start: "node index.js" } }, null, 2)}\n`); await writeFile(join(path, "index.js"), 'console.log("Hello from Rux");\n'); }
  else await writeFile(join(path, "README.md"), `# ${name}\n`);
}
function updateThread(thread: StoredThread, input: Record<string, any>): void { if (input.codexThreadId) thread.codexThreadId = input.codexThreadId; if (input.agentId) thread.agentId = input.agentId; if (input.nativeSessionId) thread.nativeSessionId = input.nativeSessionId; if (input.agentMode) thread.agentMode = input.agentMode; if (input.title) thread.title = input.title.slice(0, 100); }

export function registerWorkspaceIpc(ipc: IpcRegistrar, deps: Dependencies): void {
  ipc.handle("projects:list", deps.loadWorkspace);
  ipc.handle("messages:list", async () => {
    const fallback = deps.stateDatabase().loadMessages();
    return deps.nativeHistory ? await deps.nativeHistory.load(await deps.loadWorkspace(), fallback) : fallback;
  });
  ipc.handle("messages:save", async (_event, value) => {
    if (Buffer.byteLength(JSON.stringify(value ?? {}), "utf8") > 20 * 1024 * 1024) throw new Error("会话数据超过 20 MB 上限");
    const messages = parseInput(messagesStoreSchema, value ?? {});
    const filtered = deps.nativeHistory ? deps.nativeHistory.filterFallback(await deps.loadWorkspace(), messages, deps.stateDatabase().messageThreadIds()) : messages;
    deps.stateDatabase().saveMessages(filtered);
    return { saved: true };
  });
  ipc.handle("projects:default-parent", async () => { const path = join(app.getPath("documents"), "Rux Projects"); await mkdir(path, { recursive: true }); return path; });
  ipc.handle("projects:choose-directory", async () => { const options = { properties: ["openDirectory", "createDirectory"] as Array<"openDirectory" | "createDirectory"> }; const window = deps.getWindow(); const result = window ? await dialog.showOpenDialog(window, options) : await dialog.showOpenDialog(options); return result.canceled ? null : result.filePaths[0]; });
  ipc.handle("projects:import", async (_event, value) => { const input = parseInput(projectImportSchema, value); const path = resolve(input.path); if (!(await stat(path)).isDirectory()) throw new Error("请选择项目文件夹"); const workspace = await deps.loadWorkspace(); let project = workspace.projects.find((item) => item.path === path); if (!project) { project = { id: randomUUID(), name: basename(path), path, threads: input.createThread === false ? [] : [{ id: randomUUID(), title: "项目会话" }] }; workspace.projects.push(project); await deps.saveWorkspace(workspace); } return project; });
  ipc.handle("projects:clone", async (_event, value) => { const input = parseInput(projectCloneSchema, value); if (!/^(https?:\/\/|git@)/.test(input.url)) throw new Error("Git 地址无效"); const parent = resolve(input.parent); await mkdir(parent, { recursive: true }); const result = await deps.runProcess(deps.gitExecutable(), ["clone", "--", input.url], { cwd: parent, timeoutMs: 10 * 60_000 }); if (result.code !== 0) throw new Error(result.stderr.trim() || "克隆失败"); const folder = basename(input.url.replace(/\.git$/, "")); const project: StoredProject = { id: randomUUID(), name: folder, path: join(parent, folder), threads: input.createThread === false ? [] : [{ id: randomUUID(), title: "项目会话" }] }; const workspace = await deps.loadWorkspace(); workspace.projects.push(project); await deps.saveWorkspace(workspace); return project; });
  ipc.handle("projects:create", async (_event, value) => { const input = parseInput(projectCreateSchema, value); const name = projectName(input.name); const parent = resolve(input.parent); if (!isAbsolute(parent)) throw new Error("保存位置无效"); await mkdir(parent, { recursive: true }); const path = join(parent, name); if (await exists(path)) throw new Error("同名项目已存在"); await mkdir(path); try { await createTemplate(path, input.template, name); if (input.initGit) { const result = await deps.runProcess(deps.gitExecutable(), ["init"], { cwd: path, timeoutMs: 30_000 }); if (result.code !== 0) throw new Error(result.stderr.trim() || "Git 初始化失败"); } const project: StoredProject = { id: randomUUID(), name, path, threads: input.createThread === false ? [] : [{ id: randomUUID(), title: "项目会话" }] }; const workspace = await deps.loadWorkspace(); workspace.projects.push(project); await deps.saveWorkspace(workspace); return project; } catch (error) { await rm(path, { recursive: true, force: true }).catch(() => {}); throw error; } });
  ipc.handle("projects:remove", async (_event, value) => { const id = parseInput(projectIdSchema, value); const workspace = await deps.loadWorkspace(); const index = workspace.projects.findIndex((item) => item.id === id); if (index < 0) throw new Error("项目不存在"); const [project] = workspace.projects.splice(index, 1); await deps.saveWorkspace(workspace); return { project, workspace }; });
  ipc.handle("projects:add-thread", async (_event, value) => { const input = parseInput(addProjectThreadSchema, value); const workspace = await deps.loadWorkspace(); const project = workspace.projects.find((item) => item.id === input.projectId); if (!project) throw new Error("项目不存在"); const thread = { id: randomUUID(), title: String(input.title || "未命名会话").slice(0, 100) }; project.threads.push(thread); await deps.saveWorkspace(workspace); return thread; });
  ipc.handle("projects:add-standalone", async (_event, value) => { const input = parseInput(addStandaloneThreadSchema, value) ?? {}; const workspace = await deps.loadWorkspace(); const thread = { id: randomUUID(), title: String(input.title || "未命名会话").slice(0, 100) }; workspace.standaloneThreads.push(thread); await deps.saveWorkspace(workspace); return thread; });
  ipc.handle("projects:update-thread", async (_event, value) => { const input = parseInput(projectThreadUpdateSchema, value); const workspace = await deps.loadWorkspace(); const thread = workspace.projects.find((item) => item.id === input.projectId)?.threads.find((item) => item.id === input.threadId); if (!thread) throw new Error("会话不存在"); updateThread(thread, input); await deps.saveWorkspace(workspace); if (input.nativeSessionId || input.codexThreadId) deps.nativeHistory?.markAuthoritative(input.threadId); return thread; });
  ipc.handle("threads:update", async (_event, value) => { const input = parseInput(threadUpdateSchema, value); const workspace = await deps.loadWorkspace(); const thread = input.type === "project" ? workspace.projects.find((item) => item.id === input.projectId)?.threads.find((item) => item.id === input.threadId) : workspace.standaloneThreads.find((item) => item.id === input.threadId); if (!thread) throw new Error("会话不存在"); updateThread(thread, input); await deps.saveWorkspace(workspace); if (input.nativeSessionId || input.codexThreadId) deps.nativeHistory?.markAuthoritative(input.threadId); return thread; });
  ipc.handle("threads:remove", async (_event, value) => { const input = parseInput(threadUpdateSchema, value); const workspace = await deps.loadWorkspace(); const threads = input.type === "project" ? workspace.projects.find((item) => item.id === input.projectId)?.threads : workspace.standaloneThreads; if (!threads) throw new Error("会话不存在"); const index = threads.findIndex((item) => item.id === input.threadId); if (index < 0) throw new Error("会话不存在"); const [thread] = threads.splice(index, 1); await deps.saveWorkspace(workspace); return { thread, workspace }; });
}
