import { Button, Select, Tabs, TabsList, Tab, TabPanel } from "../ui";
import { useMemo } from "react";
import { ArrowLeft, CheckCircle, CircleNotch, File, FileText, GitBranch, WarningCircle } from "../ui/icons";
import type { GitState } from "../renderer/types";

type Props = { gitState: GitState; branches: string[]; selectedFile: string; diff: string; busy: boolean; loading?: boolean; diffLoading?: boolean; error?: string; comparisonBase?: string; onRetry?: () => void; onSelectFile: (path: string) => void; onBack: () => void; onSwitchBranch: (branch: string) => void; onCommitPush: () => void; onStageAll: () => void; onStageFile: () => void; onDiscard: () => void };

export default function ReviewScreen(props: Props) {
  const selected = props.gitState.files.find((file) => file.path === props.selectedFile);
  const locked = props.busy || props.loading;
  const lines = useMemo(() => props.diff.split("\n").map((line, index) => <span key={index} className={line.startsWith("@@") ? "diff-line is-hunk" : line.startsWith("+") && !line.startsWith("+++") ? "diff-line is-added" : line.startsWith("-") && !line.startsWith("---") ? "diff-line is-removed" : "diff-line"}>{line}{"\n"}</span>), [props.diff]);
  return <div className="review-screen">
    <Tabs value="review" onValueChange={(value) => { if (value === "conversation") props.onBack(); }}><TabsList aria-label="对话与审查"><Tab value="conversation">对话</Tab><Tab value="review">{props.comparisonBase ? "分支比较" : "变更"} <span>{props.gitState.files.length}</span></Tab></TabsList><TabPanel value="review">
    <div className="review-summary"><span><FileText size="md" />{props.comparisonBase ? `相对 ${props.comparisonBase} 的 ${props.gitState.files.length} 个变更` : `${props.gitState.files.length} 个文件变更`}</span><label className="review-branch"><GitBranch size="md" />{props.comparisonBase ? <strong>{props.gitState.branch}</strong> : <Select aria-label="切换 Git 分支" value={props.gitState.branch || ""} onValueChange={props.onSwitchBranch} disabled={locked || props.gitState.branch === "—"} options={props.branches.length ? props.branches.map((branch) => ({ value: branch, label: branch })) : [{ value: props.gitState.branch || "", label: props.gitState.branch || "—" }]} />}</label><Button variant="secondary" type="button" className="secondary-button" disabled={Boolean(props.comparisonBase) || locked || props.gitState.branch === "—"} title={props.comparisonBase ? "分支比较视图不可提交" : "提交已暂存内容或推送当前分支"} onClick={props.onCommitPush}>提交或推送</Button></div>
    {props.error ? <div className="review-empty is-error" role="alert"><WarningCircle size="xl" /><h2>无法读取 Git 状态</h2><p>{props.error}</p><Button variant="secondary" type="button" className="secondary-button" onClick={props.onRetry}>重试</Button></div> : props.loading && !props.gitState.files.length ? <div className="review-empty" role="status"><CircleNotch size="lg" className="spin" /><p>正在读取变更…</p></div> : props.gitState.files.length ? <div className="review-workspace" aria-busy={props.loading}>
      <div className="file-list" aria-label="变更文件">{props.gitState.files.map((file) => <Button variant="plain" type="button" key={file.path} title={file.path} aria-current={props.selectedFile === file.path ? "true" : undefined} className={props.selectedFile === file.path ? "is-selected" : ""} onClick={() => props.onSelectFile(file.path)}><File size="sm" /><span>{file.path}</span><small>{file.staged && <i>已暂存</i>}{file.unstaged && !file.untracked && <i>未暂存</i>}<b>+{file.plus}</b> <em>−{file.minus}</em></small></Button>)}</div>
      <div className="real-diff-wrap"><div className="diff-heading" title={props.selectedFile}>{props.selectedFile}</div><pre className="real-diff" tabIndex={0} aria-label="文件差异" aria-busy={props.diffLoading}>{props.diffLoading ? "正在加载文件差异…" : props.diff ? lines : "此文件没有可显示的文本差异（可能为二进制文件或仅元数据变更）"}</pre></div>
    </div> : <div className="review-empty"><CheckCircle size="xl" /><h2>{props.comparisonBase ? "与比较分支没有差异" : props.gitState.branch === "—" ? "当前项目不是 Git 仓库" : "工作区没有变更"}</h2></div>}
    <div className="review-actions">{!props.comparisonBase && <><Button variant="primary" type="button" className="primary-button" disabled={locked || !props.gitState.files.some((file) => file.unstaged || file.untracked)} onClick={props.onStageAll}>全部暂存</Button><Button variant="secondary" type="button" className="secondary-button" disabled={locked || !(selected?.unstaged || selected?.untracked)} onClick={props.onStageFile}>暂存此文件</Button><Button variant="plain" type="button" className="danger-link" disabled={locked || !selected?.unstaged || selected.untracked} onClick={props.onDiscard}>放弃未暂存修改</Button></>}<Button variant="plain" type="button" className="back-to-chat" onClick={props.onBack}><ArrowLeft size="sm" />返回对话</Button></div>
    </TabPanel></Tabs>
  </div>;
}
