import { useMemo } from "react";
import { ArrowLeft, CheckCircle, CircleNotch, File, FileText, GitBranch, WarningCircle } from "@phosphor-icons/react";
import type { GitState } from "../renderer/types";

type Props = { gitState: GitState; branches: string[]; selectedFile: string; diff: string; busy: boolean; loading?: boolean; diffLoading?: boolean; error?: string; comparisonBase?: string; onRetry?: () => void; onSelectFile: (path: string) => void; onBack: () => void; onSwitchBranch: (branch: string) => void; onCommitPush: () => void; onStageAll: () => void; onStageFile: () => void; onDiscard: () => void };

export default function ReviewScreen(props: Props) {
  const selected = props.gitState.files.find((file) => file.path === props.selectedFile);
  const locked = props.busy || props.loading;
  const lines = useMemo(() => props.diff.split("\n").map((line, index) => <span key={index} className={line.startsWith("@@") ? "diff-line is-hunk" : line.startsWith("+") && !line.startsWith("+++") ? "diff-line is-added" : line.startsWith("-") && !line.startsWith("---") ? "diff-line is-removed" : "diff-line"}>{line}{"\n"}</span>), [props.diff]);
  return <div className="review-screen">
    <div className="review-tabs"><button type="button" onClick={props.onBack}>对话</button><button type="button" className="is-active">{props.comparisonBase ? "分支比较" : "变更"} <span>{props.gitState.files.length}</span></button></div>
    <div className="review-summary"><span><FileText size={18} />{props.comparisonBase ? `相对 ${props.comparisonBase} 的 ${props.gitState.files.length} 个变更` : `${props.gitState.files.length} 个文件变更`}</span><label className="review-branch"><GitBranch size={18} />{props.comparisonBase ? <strong>{props.gitState.branch}</strong> : <select aria-label="切换 Git 分支" value={props.gitState.branch || ""} onChange={(event) => props.onSwitchBranch(event.target.value)} disabled={locked || props.gitState.branch === "—"}>{props.branches.length ? props.branches.map((branch) => <option value={branch} key={branch}>{branch}</option>) : <option value={props.gitState.branch || ""}>{props.gitState.branch || "—"}</option>}</select>}</label><button type="button" className="secondary-button" disabled={Boolean(props.comparisonBase) || locked || props.gitState.branch === "—"} title={props.comparisonBase ? "分支比较视图不可提交" : "提交已暂存内容或推送当前分支"} onClick={props.onCommitPush}>提交或推送</button></div>
    {props.error ? <div className="review-empty is-error" role="alert"><WarningCircle size={30} /><h2>无法读取 Git 状态</h2><p>{props.error}</p><button type="button" className="secondary-button" onClick={props.onRetry}>重试</button></div> : props.loading && !props.gitState.files.length ? <div className="review-empty" role="status"><CircleNotch size={26} className="spin" /><p>正在读取变更…</p></div> : props.gitState.files.length ? <div className="review-workspace" aria-busy={props.loading}>
      <div className="file-list" aria-label="变更文件">{props.gitState.files.map((file) => <button type="button" key={file.path} title={file.path} aria-current={props.selectedFile === file.path ? "true" : undefined} className={props.selectedFile === file.path ? "is-selected" : ""} onClick={() => props.onSelectFile(file.path)}><File size={17} /><span>{file.path}</span><small>{file.staged && <i>已暂存</i>}{file.unstaged && !file.untracked && <i>未暂存</i>}<b>+{file.plus}</b> <em>−{file.minus}</em></small></button>)}</div>
      <div className="real-diff-wrap"><div className="diff-heading" title={props.selectedFile}>{props.selectedFile}</div><pre className="real-diff" tabIndex={0} aria-label="文件差异" aria-busy={props.diffLoading}>{props.diffLoading ? "正在加载文件差异…" : props.diff ? lines : "此文件没有可显示的文本差异（可能为二进制文件或仅元数据变更）"}</pre></div>
    </div> : <div className="review-empty"><CheckCircle size={30} /><h2>{props.comparisonBase ? "与比较分支没有差异" : props.gitState.branch === "—" ? "当前项目不是 Git 仓库" : "工作区没有变更"}</h2></div>}
    <div className="review-actions">{!props.comparisonBase && <><button type="button" className="primary-button" disabled={locked || !props.gitState.files.some((file) => file.unstaged || file.untracked)} onClick={props.onStageAll}>全部暂存</button><button type="button" className="secondary-button" disabled={locked || !(selected?.unstaged || selected?.untracked)} onClick={props.onStageFile}>暂存此文件</button><button type="button" className="danger-link" disabled={locked || !selected?.unstaged || selected.untracked} onClick={props.onDiscard}>放弃未暂存修改</button></>}<button type="button" className="back-to-chat" onClick={props.onBack}><ArrowLeft size={16} />返回对话</button></div>
  </div>;
}
