import { useCallback, useEffect, useState } from "react";
import type { RuxApi } from "../../electron/preload";
import type { AppSettings } from "./useAppBootstrap";
import type { WorkspaceToolId } from "../types";
import { userFacingError } from "../errors";
import { useTerminalController } from "./useTerminalController";

type SideMessage = { id: string; role: "user" | "assistant"; text: string };
const projectOnlyTools = new Set<WorkspaceToolId>(["review", "terminal", "browser", "files"]);

export function useWorkspaceTools(api: RuxApi, projectId: string | undefined, settings: AppSettings, refreshGit: (projectId?: string) => Promise<void>, notify: (message: string) => void) {
  const [bottomPanelOpen, setBottomPanelOpen] = useState(false); const [rightPanelOpen, setRightPanelOpen] = useState(false); const [activeTool, setActiveTool] = useState<WorkspaceToolId>("terminal");
  const [projectFiles, setProjectFiles] = useState<string[]>([]); const [remoteUrl, setRemoteUrl] = useState(""); const [sideMessages, setSideMessages] = useState<SideMessage[]>([]); const [sideValue, setSideValue] = useState(""); const [sideSending, setSideSending] = useState(false); const [sideThreadId, setSideThreadId] = useState("");
  const terminal = useTerminalController(api, projectId, () => { void refreshGit(); }, notify);
  useEffect(() => { if (projectId) { api.files.list(projectId).then((files) => setProjectFiles(files as string[])).catch(() => setProjectFiles([])); api.git.remote(projectId).then((url) => setRemoteUrl(String(url))).catch(() => setRemoteUrl("")); } else { setProjectFiles([]); setRemoteUrl(""); } setSideMessages([]); setSideThreadId(""); setSideValue(""); }, [api, projectId]);
  const closeBottomPanel = useCallback(async () => { await terminal.closeTerminal(); setBottomPanelOpen(false); }, [terminal.closeTerminal]);
  const toggleBottomPanel = useCallback(async () => { if (bottomPanelOpen) { await closeBottomPanel(); return; } setBottomPanelOpen(true); if (activeTool === "terminal") await terminal.startTerminal(); }, [activeTool, bottomPanelOpen, closeBottomPanel, terminal.startTerminal]);
  const selectWorkspaceTool = useCallback(async (tool: WorkspaceToolId) => { if (projectOnlyTools.has(tool) && !projectId) { notify("请先选择一个项目会话"); return; } setActiveTool(tool); setBottomPanelOpen(true); if (tool === "terminal") await terminal.startTerminal(); if (tool === "review") await refreshGit(projectId); if (tool === "files" && projectId) api.files.list(projectId).then((files) => setProjectFiles(files as string[])).catch((error) => notify(error instanceof Error ? error.message : String(error))); if (tool === "browser" && projectId) api.git.remote(projectId).then((url) => setRemoteUrl(String(url))).catch(() => setRemoteUrl("")); }, [api, notify, projectId, refreshGit, terminal.startTerminal]);
  const openRemote = useCallback(async () => { if (!projectId) return; try { const remote = String(await api.git.remote(projectId)); if (!remote) { notify("当前项目没有 origin 远程地址"); return; } const url = remote.startsWith("git@") ? `https://${remote.slice(4).replace(":", "/").replace(/\.git$/, "")}` : remote.replace(/\.git$/, ""); await api.system.openExternal(url); } catch (error) { notify(error instanceof Error ? error.message : String(error)); } }, [api, notify, projectId]);
  const sendSideChat = useCallback(async () => { const prompt = sideValue.trim(); if (!prompt || sideSending) return; const user: SideMessage = { id: crypto.randomUUID(), role: "user", text: prompt }; setSideMessages((current) => [...current, user]); setSideValue(""); setSideSending(true); try { const result = await api.agent.send({ projectId, prompt, model: settings.model, reasoning: settings.reasoning, sandboxMode: settings.sandboxMode, threadId: sideThreadId || undefined }) as { text: string; threadId?: string }; setSideMessages((current) => [...current, { id: crypto.randomUUID(), role: "assistant", text: result.text }]); if (result.threadId) setSideThreadId(result.threadId); } catch (error) { setSideMessages((current) => [...current, { id: crypto.randomUUID(), role: "assistant", text: userFacingError(error) }]); } finally { setSideSending(false); } }, [api, projectId, settings, sideSending, sideThreadId, sideValue]);
  return { bottomPanelOpen, setBottomPanelOpen, rightPanelOpen, setRightPanelOpen, activeTool, projectFiles, remoteUrl, sideMessages, sideValue, setSideValue, sideSending, closeBottomPanel, toggleBottomPanel, selectWorkspaceTool, openRemote, sendSideChat, ...terminal };
}
