export const workspaces = [
  {
    id: "rux",
    name: "Rux",
    path: "~/projects/rux",
    branch: "main",
    tone: "ink",
  },
  {
    id: "jiali",
    name: "jiali",
    path: "~/projects/jiali",
    branch: "main",
    tone: "blue",
  },
  {
    id: "xxyy-ask",
    name: "xxyy-ask",
    path: "~/projects/xxyy-ask",
    branch: "main",
    tone: "sand",
  },
  { id: "resume-os", name: "resume-os", path: "~/projects/resume-os", branch: "main", tone: "ink" },
  { id: "tg-draw-farmer", name: "tg-draw-farmer", path: "~/projects/tg-draw-farmer", branch: "main", tone: "blue" },
  { id: "xiaohongshu-ops", name: "xiaohongshu-ops", path: "~/projects/xiaohongshu-ops", branch: "main", tone: "ink" },
  { id: "stepsensation", name: "stepsensation", path: "~/projects/stepsensation", branch: "main", tone: "sand" },
  { id: "wty", name: "wty", path: "~/projects/wty", branch: "main", tone: "ink" },
  { id: "dev-labs", name: "dev-labs", path: "~/projects/dev-labs", branch: "main", tone: "blue" },
  { id: "ai-translate", name: "ai-translate", path: "~/projects/ai-translate", branch: "main", tone: "sand" },
];

export const initialTasks = [
  {
    id: "service-check",
    pinned: true,
    workspaceId: "rux",
    title: "检查服务器运行服务",
    preview: "服务检查已完成",
    status: "completed",
    updatedAt: "刚刚",
    agent: "Codex",
    adapter: "mock",
    model: "GPT-5.6 Sol",
    branch: "main",
    elapsed: "42秒",
    tokens: "8.1k",
    messages: [{ id: "service-check-result", role: "assistant", text: "服务检查已完成，当前进程运行正常。", time: "刚刚" }],
    plan: [],
    activity: [],
  },
  {
    id: "devspace-intro",
    pinned: true,
    workspaceId: "rux",
    title: "介绍 Devspace 项目",
    preview: "已修复并更新服务",
    status: "completed",
    updatedAt: "刚刚",
    agent: "Codex",
    adapter: "mock",
    permissionMode: "dontAsk",
    model: "GPT-5.6 Sol",
    branch: "main",
    elapsed: "2分钟 3秒",
    tokens: "28.4k",
    messages: [
      {
        id: "devspace-result",
        role: "assistant",
        text: "已修复并更新服务。\n\n现在切换后台 Tab 时，URL 会同步为：\n\n```text\n/admin?tab=telegram-users\n```\n\n刷新页面会保持当前 Tab，浏览器前进/后退也能恢复对应 Tab。\n\n验证结果：\n\n- **979 项测试通过**\n- RAG 评估 60/60\n- API 已重启，健康检查正常\n- 未提交 Git commit",
        time: "刚刚",
      },
    ],
    plan: [],
    activity: [],
  },
  {
    id: "desktop-workbench",
    pinned: false,
    workspaceId: "rux",
    title: "实现 Rux 桌面工作台",
    preview: "已完成桌面工作台重构与视觉验证",
    status: "completed",
    updatedAt: "刚刚",
    agent: "Codex",
    model: "GPT-5.6",
    branch: "rux/desktop-workbench",
    elapsed: "8s",
    tokens: "28.4k",
    messages: [
      {
        id: "m1",
        role: "user",
        text: "先实现一个 Rux 桌面工作台。要有项目与任务侧栏、Agent 执行时间线、Diff Review、Context Inspector 和集成终端。",
        time: "15:42",
      },
    ],
    plan: [
      { label: "读取产品需求和视觉基准", state: "done" },
      { label: "实现工作区、任务与执行时间线", state: "done" },
      { label: "接入 Changes、Context 与 Terminal", state: "done" },
      { label: "运行构建并完成视觉 QA", state: "done" },
    ],
    activity: [
      {
        id: "a1",
        kind: "read",
        title: "读取产品需求",
        detail: "README.md · docs/product-requirements.md",
        state: "done",
      },
      {
        id: "a2",
        kind: "command",
        title: "创建桌面原型",
        detail: "npm install · Vite + React",
        state: "done",
      },
      {
        id: "a3",
        kind: "edit",
        title: "实现主工作区",
        detail: "3 个文件已修改 · +612  -14",
        state: "done",
      },
    ],
  },
  {
    id: "prd",
    workspaceId: "rux",
    title: "整理产品需求与 MVP 范围",
    preview: "明确 Workbench-first 的产品定位",
    status: "completed",
    updatedAt: "34 分钟",
    agent: "Codex",
    model: "GPT-5.6",
    branch: "main",
    elapsed: "8m 12s",
    tokens: "16.1k",
    messages: [
      {
        id: "m-prd",
        role: "user",
        text: "把产品范围收敛成 Coding Agent Workbench，并整理成一份可执行的 PRD。",
        time: "14:58",
      },
    ],
    plan: [
      { label: "梳理核心用户和问题", state: "done" },
      { label: "定义产品对象和主流程", state: "done" },
      { label: "收敛 MVP 与非目标", state: "done" },
    ],
    activity: [
      {
        id: "a-prd-1",
        kind: "edit",
        title: "编写产品需求文档",
        detail: "docs/product-requirements.md · +486",
        state: "done",
      },
      {
        id: "a-prd-2",
        kind: "command",
        title: "检查文档结构",
        detail: "18 个章节 · 0 个断链",
        state: "done",
      },
    ],
  },
  {
    id: "market",
    workspaceId: "rux",
    title: "分析 Coding Agent 市场",
    preview: "Rux、Claude Code、Grok Build、Pi",
    status: "completed",
    updatedAt: "昨天",
    agent: "Claude Code",
    model: "Claude Opus",
    branch: "main",
    elapsed: "18m 04s",
    tokens: "42.7k",
    messages: [
      {
        id: "m-market",
        role: "user",
        text: "比较主流 Coding Agent 的体验和痛点，给出 Rux 的产品切入点。",
        time: "昨天",
      },
    ],
    plan: [
      { label: "研究桌面与 TUI 产品", state: "done" },
      { label: "提炼共性痛点", state: "done" },
      { label: "形成定位建议", state: "done" },
    ],
    activity: [
      {
        id: "a-market-1",
        kind: "read",
        title: "调研产品资料",
        detail: "12 个来源 · Rux / Claude / Grok / Pi",
        state: "done",
      },
    ],
  },
  {
    id: "adapter",
    workspaceId: "rux",
    title: "设计 Agent Runtime Adapter",
    preview: "统一事件、权限与变更协议",
    status: "waiting",
    updatedAt: "昨天",
    agent: "Claude Code",
    model: "Claude Sonnet",
    branch: "rux/runtime-adapter",
    elapsed: "—",
    tokens: "—",
    messages: [
      {
        id: "m-adapter",
        role: "user",
        text: "定义一个可以同时承载原生 Agent 与外部 Agent 的 Runtime Adapter。",
        time: "昨天",
      },
    ],
    plan: [
      { label: "定义 Run 生命周期", state: "pending" },
      { label: "统一 observable event schema", state: "pending" },
      { label: "设计权限和取消语义", state: "pending" },
    ],
    activity: [],
  },
];

export const changedFiles = [
  { name: "AdminApp.test.tsx", path: "apps/web/src/AdminApp.test.tsx", additions: 7, deletions: 1, status: "M", kind: "modified", isBinary: false },
  { name: "AdminApp.tsx", path: "apps/web/src/AdminApp.tsx", additions: 42, deletions: 2, status: "M", kind: "modified", isBinary: false },
];

export const diffByFile = {
  "src/App.jsx": [
    { type: "meta", old: "@@ -1,5 +1,18 @@", next: "" },
    { type: "same", old: "1", next: "1", code: "import React, { useMemo, useState } from \"react\";" },
    { type: "add", old: "", next: "2", code: "import { Activity, GitBranch, Terminal } from \"lucide-react\";" },
    { type: "add", old: "", next: "3", code: "import { initialTasks, workspaces } from \"./data.js\";" },
    { type: "same", old: "2", next: "4", code: "" },
    { type: "remove", old: "3", next: "", code: "export function App() { return <main />; }" },
    { type: "add", old: "", next: "5", code: "export function App() {" },
    { type: "add", old: "", next: "6", code: "  const [selectedTaskId, setSelectedTaskId] = useState(\"desktop-workbench\");" },
    { type: "add", old: "", next: "7", code: "  const [inspectorTab, setInspectorTab] = useState(\"changes\");" },
    { type: "add", old: "", next: "8", code: "  return <div className=\"app-shell\">…</div>;" },
    { type: "add", old: "", next: "9", code: "}" },
  ],
  "src/styles.css": [
    { type: "meta", old: "@@ -1,6 +1,14 @@", next: "" },
    { type: "same", old: "1", next: "1", code: ":root {" },
    { type: "add", old: "", next: "2", code: "  color: #1f201d;" },
    { type: "add", old: "", next: "3", code: "  background: #f7f7f5;" },
    { type: "add", old: "", next: "4", code: "  font-family: Inter, ui-sans-serif, system-ui, sans-serif;" },
    { type: "same", old: "2", next: "5", code: "}" },
    { type: "add", old: "", next: "6", code: ".app-shell { display: grid; min-height: 100dvh; }" },
  ],
  "src/runtime.js": [
    { type: "meta", old: "@@ -0,0 +1,12 @@", next: "" },
    { type: "add", old: "", next: "1", code: "export function createMockRuntime() {" },
    { type: "add", old: "", next: "2", code: "  return {" },
    { type: "add", old: "", next: "3", code: "    run(prompt, emit) {" },
    { type: "add", old: "", next: "4", code: "      emit({ type: \"run.started\", prompt });" },
    { type: "add", old: "", next: "5", code: "      return () => emit({ type: \"run.cancelled\" });" },
    { type: "add", old: "", next: "6", code: "    }," },
    { type: "add", old: "", next: "7", code: "  };" },
    { type: "add", old: "", next: "8", code: "}" },
  ],
};

export const contextGroups = [
  {
    id: "instructions",
    title: "Project instructions",
    caption: "2 sources · always included",
    items: ["AGENTS.md", "docs/product-requirements.md"],
  },
  {
    id: "files",
    title: "Selected files",
    caption: "5 files · 12.4k tokens",
    items: ["src/App.jsx", "src/styles.css", "src/data.js", "README.md", "package.json"],
  },
  {
    id: "skills",
    title: "Skills & tools",
    caption: "2 skills · 4 tools",
    items: ["Product Design", "Browser QA", "Terminal", "Git"],
  },
];
