import { useEffect, useRef, useState, type Dispatch, type SetStateAction } from "react";
import { ArrowLeft, CheckCircle, Code, DownloadSimple, Folder, FolderPlus, TerminalWindow, WarningCircle, X } from "@phosphor-icons/react";
import IconButton from "../components/IconButton";
import type { ProjectAction } from "../renderer/types";

type Step = "choose" | "import" | "create";
type Props = { step: Step; defaultParent: string; onClose: () => void; onStep: (step: Step) => void; onComplete: (action: ProjectAction) => Promise<void>; onChooseDirectory: () => Promise<string | null> };

function Header({ title, subtitle, onBack, onClose }: { title: string; subtitle: string; onBack?: () => void; onClose: () => void }) {
  return <div className="modal-header"><div className="modal-title-row">{onBack && <IconButton label="返回" onClick={onBack}><ArrowLeft size={20} /></IconButton>}<h2>{title}</h2><IconButton label="关闭" className="modal-close" onClick={onClose}><X size={20} /></IconButton></div><p>{subtitle}</p></div>;
}

export default function AddProjectModal(props: Props) {
  const backdropRef = useRef<HTMLDivElement>(null);
  const dialogRef = useRef<HTMLElement>(null);
  const [choice, setChoice] = useState<"import" | "create">("import"); const [importMode, setImportMode] = useState<"folder" | "git">("folder");
  const [folderPath, setFolderPath] = useState(""); const [gitUrl, setGitUrl] = useState(""); const [parent, setParent] = useState(props.defaultParent);
  const [projectName, setProjectName] = useState("rux-agent"); const [template, setTemplate] = useState<"empty" | "react" | "node">("empty");
  const [gitEnabled, setGitEnabled] = useState(true); const [createThread, setCreateThread] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => setParent(props.defaultParent), [props.defaultParent]);
  useEffect(() => {
    const previousFocus = document.activeElement as HTMLElement | null;
    const backdrop = backdropRef.current;
    const siblings = backdrop?.parentElement ? [...backdrop.parentElement.children].filter((element) => element !== backdrop) as HTMLElement[] : [];
    for (const sibling of siblings) { sibling.inert = true; sibling.setAttribute("aria-hidden", "true"); }
    return () => { for (const sibling of siblings) { sibling.inert = false; sibling.removeAttribute("aria-hidden"); } previousFocus?.focus(); };
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => { const dialog = dialogRef.current; const target = dialog?.querySelector<HTMLElement>("[data-autofocus]") || dialog?.querySelector<HTMLElement>("input, button"); target?.focus(); }, 0); return () => window.clearTimeout(timer); }, [importMode, props.step]);
  const onDialogKeyDown = (event: React.KeyboardEvent<HTMLElement>) => {
    if (event.key === "Escape") { event.preventDefault(); props.onClose(); return; }
    if (event.key !== "Tab") return;
    const focusable = [...(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), [tabindex]:not([tabindex="-1"])') || [])];
    if (!focusable.length) return;
    const first = focusable[0]; const last = focusable[focusable.length - 1];
    if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
    else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
  };
  async function choose(setter: Dispatch<SetStateAction<string>>) { const path = await props.onChooseDirectory(); if (path) setter(path); }
  async function submit(action: ProjectAction) { setBusy(true); setError(""); try { await props.onComplete(action); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  return <div ref={backdropRef} className="modal-backdrop" role="presentation"><section ref={dialogRef} className={`modal ${props.step === "choose" ? "choice-modal" : "form-modal"}`} role="dialog" aria-modal="true" aria-label="添加项目" tabIndex={-1} onKeyDown={onDialogKeyDown}>
    {props.step === "choose" && <><Header title="添加项目" subtitle="导入现有代码，或从零开始创建" onClose={props.onClose} /><div className="choice-list" role="group" aria-label="添加项目方式"><button data-autofocus type="button" aria-pressed={choice === "import"} className={`project-choice ${choice === "import" ? "is-selected" : ""}`} onClick={() => setChoice("import")}><span className="choice-icon"><DownloadSimple size={26} /></span><span><strong>导入已有项目</strong><small>选择本地文件夹或克隆 Git 仓库</small></span></button><button type="button" aria-pressed={choice === "create"} className={`project-choice ${choice === "create" ? "is-selected" : ""}`} onClick={() => setChoice("create")}><span className="choice-icon"><FolderPlus size={27} /></span><span><strong>新建项目</strong><small>创建空项目或从模板开始</small></span></button></div><div className="modal-footer"><button type="button" className="secondary-button" onClick={props.onClose}>取消</button><button type="button" className="primary-button" onClick={() => props.onStep(choice)}>继续</button></div></>}
    {props.step === "import" && <><Header title="导入已有项目" subtitle="选择本地文件夹，或从 Git 仓库克隆" onBack={() => props.onStep("choose")} onClose={props.onClose} /><div className="segmented-control" role="group" aria-label="导入方式"><button type="button" aria-pressed={importMode === "folder"} className={importMode === "folder" ? "is-active" : ""} onClick={() => setImportMode("folder")}>本地文件夹</button><button type="button" aria-pressed={importMode === "git"} className={importMode === "git" ? "is-active" : ""} onClick={() => setImportMode("git")}>Git 仓库</button></div>{importMode === "folder" ? <div className="form-stack"><div className="form-row"><span><strong>项目文件夹</strong><small>{folderPath || "尚未选择"}</small></span><button data-autofocus type="button" className="secondary-button" onClick={() => void choose(setFolderPath)}>选择文件夹</button></div>{folderPath && <div className="detected-project"><Folder size={30} /><span><strong>{folderPath.split(/[\\/]/).pop()}</strong><small>{folderPath}</small></span><span className="import-ok"><CheckCircle size={18} />可以导入</span></div>}</div> : <div className="form-stack"><label className="field-label">Git 仓库地址<input data-autofocus value={gitUrl} onChange={(event) => setGitUrl(event.target.value)} /></label><label className="field-label">保存位置<input value={parent} onChange={(event) => setParent(event.target.value)} /></label></div>}<label className="checkbox-row"><input type="checkbox" checked={createThread} onChange={(event) => setCreateThread(event.target.checked)} />导入后创建首个项目会话</label>{error && <p className="form-error"><WarningCircle size={16} />{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" onClick={() => props.onStep("choose")}>上一步</button><button type="button" className="primary-button" disabled={busy || (importMode === "folder" ? !folderPath : !gitUrl)} onClick={() => void submit(importMode === "folder" ? { kind: "import", path: folderPath, createThread } : { kind: "clone", url: gitUrl, parent, createThread })}>{busy ? "处理中…" : "导入项目"}</button></div></>}
    {props.step === "create" && <><Header title="新建项目" subtitle="创建一个新的本地项目" onBack={() => props.onStep("choose")} onClose={props.onClose} /><div className="form-stack create-form"><label className="field-label">项目名称<input data-autofocus value={projectName} onChange={(event) => setProjectName(event.target.value)} /></label><div className="form-row"><span><strong>保存位置</strong><small>{parent}</small></span><button type="button" className="secondary-button" onClick={() => void choose(setParent)}>选择位置</button></div><fieldset className="template-fieldset"><legend>起始模板</legend><div className="template-options" role="group" aria-label="起始模板">{[["empty", "空项目", <Folder key="folder" size={19} />], ["react", "React", <Code key="react" size={19} />], ["node", "Node.js", <TerminalWindow key="node" size={19} />]].map(([id, title, icon]) => <button type="button" key={String(id)} aria-pressed={template === id} className={template === id ? "is-selected" : ""} onClick={() => setTemplate(id as typeof template)}>{icon}{title}</button>)}</div></fieldset><label className="toggle-row"><span>初始化 Git 仓库</span><input type="checkbox" checked={gitEnabled} onChange={(event) => setGitEnabled(event.target.checked)} /><span className="toggle-control" /></label><label className="checkbox-row"><input type="checkbox" checked={createThread} onChange={(event) => setCreateThread(event.target.checked)} />创建后新建项目会话</label><div className="path-preview">{parent}/{projectName || "新项目"}</div></div>{error && <p className="form-error"><WarningCircle size={16} />{error}</p>}<div className="modal-footer"><button type="button" className="secondary-button" onClick={() => props.onStep("choose")}>上一步</button><button type="button" className="primary-button" disabled={busy || !projectName.trim()} onClick={() => void submit({ kind: "create", name: projectName, parent, template, initGit: gitEnabled, createThread })}>{busy ? "创建中…" : "创建项目"}</button></div></>}
  </section></div>;
}
