import { Button, Input, Modal, Switch, Checkbox, SegmentedControl } from "../ui";
import { useEffect, useRef, useState, type Dispatch, type SetStateAction } from "react";
import { ArrowLeft, CheckCircle, Code, DownloadSimple, Folder, FolderPlus, TerminalWindow, WarningCircle, X } from "../ui/icons";
import IconButton from "../components/IconButton";
import type { ProjectAction } from "../renderer/types";

type Step = "choose" | "import" | "create";
type Props = { step: Step; defaultParent: string; onClose: () => void; onStep: (step: Step) => void; onComplete: (action: ProjectAction) => Promise<void>; onChooseDirectory: () => Promise<string | null> };

function Header({ title, subtitle, onBack, onClose }: { title: string; subtitle: string; onBack?: () => void; onClose: () => void }) {
  return <div className="modal-header"><div className="modal-title-row">{onBack && <IconButton label="返回" onClick={onBack}><ArrowLeft size="md" /></IconButton>}<h2>{title}</h2><IconButton label="关闭" className="modal-close" onClick={onClose}><X size="md" /></IconButton></div><p>{subtitle}</p></div>;
}

export default function AddProjectModal(props: Props) {
  const [choice, setChoice] = useState<"import" | "create">("import"); const [importMode, setImportMode] = useState<"folder" | "git">("folder");
  const [folderPath, setFolderPath] = useState(""); const [gitUrl, setGitUrl] = useState(""); const [parent, setParent] = useState(props.defaultParent);
  const [projectName, setProjectName] = useState("rux-agent"); const [template, setTemplate] = useState<"empty" | "react" | "node">("empty");
  const [gitEnabled, setGitEnabled] = useState(true); const [createThread, setCreateThread] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => setParent(props.defaultParent), [props.defaultParent]);
  async function choose(setter: Dispatch<SetStateAction<string>>) { const path = await props.onChooseDirectory(); if (path) setter(path); }
  async function submit(action: ProjectAction) { setBusy(true); setError(""); try { await props.onComplete(action); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  return <Modal label="添加项目" onClose={props.onClose} busy={busy} focusKey={`${props.step}:${importMode}`} className={props.step === "choose" ? "choice-modal" : "form-modal"}>
    {props.step === "choose" && <><Header title="添加项目" subtitle="导入现有代码，或从零开始创建" onClose={props.onClose} /><div className="choice-list" role="group" aria-label="添加项目方式"><Button variant="plain" data-autofocus type="button" aria-pressed={choice === "import"} className={`project-choice ${choice === "import" ? "is-selected" : ""}`} onClick={() => setChoice("import")}><span className="choice-icon"><DownloadSimple size="lg" /></span><span><strong>导入已有项目</strong><small>选择本地文件夹或克隆 Git 仓库</small></span></Button><Button variant="plain" type="button" aria-pressed={choice === "create"} className={`project-choice ${choice === "create" ? "is-selected" : ""}`} onClick={() => setChoice("create")}><span className="choice-icon"><FolderPlus size="lg" /></span><span><strong>新建项目</strong><small>创建空项目或从模板开始</small></span></Button></div><div className="modal-footer"><Button variant="secondary" type="button" className="secondary-button" onClick={props.onClose}>取消</Button><Button variant="primary" type="button" className="primary-button" onClick={() => props.onStep(choice)}>继续</Button></div></>}
    {props.step === "import" && <><Header title="导入已有项目" subtitle="选择本地文件夹，或从 Git 仓库克隆" onBack={() => props.onStep("choose")} onClose={props.onClose} /><SegmentedControl label="导入方式" value={importMode} onValueChange={(value) => setImportMode(value as "folder" | "git")} options={[{ value: "folder", label: "本地文件夹" }, { value: "git", label: "Git 仓库" }]} />{importMode === "folder" ? <div className="form-stack"><div className="form-row"><span><strong>项目文件夹</strong><small>{folderPath || "尚未选择"}</small></span><Button variant="secondary" data-autofocus type="button" className="secondary-button" onClick={() => void choose(setFolderPath)}>选择文件夹</Button></div>{folderPath && <div className="detected-project"><Folder size="xl" /><span><strong>{folderPath.split(/[\\/]/).pop()}</strong><small>{folderPath}</small></span><span className="import-ok"><CheckCircle size="md" />可以导入</span></div>}</div> : <div className="form-stack"><label className="field-label">Git 仓库地址<Input data-autofocus value={gitUrl} onChange={(event) => setGitUrl(event.target.value)} /></label><label className="field-label">保存位置<Input value={parent} onChange={(event) => setParent(event.target.value)} /></label></div>}<label className="checkbox-row"><Checkbox checked={createThread} onCheckedChange={(value) => setCreateThread(value === true)} />导入后创建首个项目会话</label>{error && <p className="form-error"><WarningCircle size="sm" />{error}</p>}<div className="modal-footer"><Button variant="secondary" type="button" className="secondary-button" onClick={() => props.onStep("choose")}>上一步</Button><Button variant="primary" type="button" className="primary-button" disabled={busy || (importMode === "folder" ? !folderPath : !gitUrl)} onClick={() => void submit(importMode === "folder" ? { kind: "import", path: folderPath, createThread } : { kind: "clone", url: gitUrl, parent, createThread })}>{busy ? "处理中…" : "导入项目"}</Button></div></>}
    {props.step === "create" && <><Header title="新建项目" subtitle="创建一个新的本地项目" onBack={() => props.onStep("choose")} onClose={props.onClose} /><div className="form-stack create-form"><label className="field-label">项目名称<Input data-autofocus value={projectName} onChange={(event) => setProjectName(event.target.value)} /></label><div className="form-row"><span><strong>保存位置</strong><small>{parent}</small></span><Button variant="secondary" type="button" className="secondary-button" onClick={() => void choose(setParent)}>选择位置</Button></div><fieldset className="template-fieldset"><legend>起始模板</legend><div className="template-options" role="group" aria-label="起始模板">{[["empty", "空项目", <Folder key="folder" size="md" />], ["react", "React", <Code key="react" size="md" />], ["node", "Node.js", <TerminalWindow key="node" size="md" />]].map(([id, title, icon]) => <Button variant="plain" type="button" key={String(id)} aria-pressed={template === id} className={template === id ? "is-selected" : ""} onClick={() => setTemplate(id as typeof template)}>{icon}{title}</Button>)}</div></fieldset><label className="toggle-row"><span>初始化 Git 仓库</span><Switch checked={gitEnabled} onCheckedChange={setGitEnabled} /></label><label className="checkbox-row"><Checkbox checked={createThread} onCheckedChange={(value) => setCreateThread(value === true)} />创建后新建项目会话</label><div className="path-preview">{parent}/{projectName || "新项目"}</div></div>{error && <p className="form-error"><WarningCircle size="sm" />{error}</p>}<div className="modal-footer"><Button variant="secondary" type="button" className="secondary-button" onClick={() => props.onStep("choose")}>上一步</Button><Button variant="primary" type="button" className="primary-button" disabled={busy || !projectName.trim()} onClick={() => void submit({ kind: "create", name: projectName, parent, template, initGit: gitEnabled, createThread })}>{busy ? "创建中…" : "创建项目"}</Button></div></>}
  </Modal>;
}
